### ISSUE TITLE
Items that are blocking the registration of StrideArrays in the General registry

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/StrideArrays.jl#2]
1. Remove threading utils and depend on ThreadingUtilities.jl (#1)
2. Remove matmul code and depend on Octavian.jl

Anything else that needs to be done before we register StrideArrays?

**Comment by chriselrod** [comment]
That about sums it up.

**Comment by DilumAluthge** [comment]
Looks like both number 1 and number 2 are done?

What do you think about registering an initial version now?

**Comment by chriselrod** [comment]
Done.
