### ISSUE TITLE
only first dimension is static using @StrideArray rand(...)

### ISSUE THREAD

**Issue by Roger-luo** [chriselrod/StrideArrays.jl#22]
I tried to create the following array to represent complex matrices

```julia
S = @StrideArray rand(Float64, 2, 100, 1<<20)
U = @StrideArray rand(Float64, 2, 1<<3, 1<<3)
```

where I was expecting the second and last dimension to be static as well, but

```julia
julia> ArrayInterface.size(S)
(static(2), static(100), 1048576)

julia> ArrayInterface.size(U)
(static(2), 8, 8)
```

not sure how to make `U` entirely static sized?

---
update: I think I understand why, It seems this macro won't evaluate the constant expression, so `1<<3` is evaluated at runtime, perhaps for this case, `@StrideArray` should support the `$` mark?

**Comment by chriselrod** [comment]
> update: I think I understand why, It seems this macro won't evaluate the constant expression, so 1<<3 is evaluated at runtime, perhaps for this case, @StrideArray should support the $ mark?

Yeah. My assumption was that if it's an expression, it might not be known at compile time, so better to make the array dim dynamic (and type stable).
`Static.StaticInt`s define static dimensions, so this is a more verbose way of doing it:
```julia
julia> using Static: One

julia> using StrideArrays

julia> n = StaticInt(3)
static(3)

julia> @StrideArray rand(Float32, 4, One() << n)
4×8 StrideMatrix{Tuple{StaticInt{4}, StaticInt{8}}, (true, true), Float32, 1, 0, (1, 2), Tuple{StaticInt{4}, StaticInt{16}}, Tuple{StaticInt{1}, StaticInt{1}}, Octavian.MemoryBuffer{32, Float32}} with indices static(1):static(4)×static(1):static(8):
 0.24028    0.558867   0.719435  0.332867  0.179933  0.267048   0.249032   0.225379
 0.0525777  0.0422457  0.356581  0.813581  0.345833  0.385433   0.181159   0.434743
 0.913041   0.184362   0.551249  0.890395  0.576048  0.0816525  0.481346   0.428838
 0.94718    0.0859883  0.966138  0.390005  0.047424  0.912956   0.0651259  0.434738

julia> StrideArrays.size(ans) # StrideArrays.size === ArrayInterface.size
(static(4), static(8))
```
So using `$` as a way to assert that either inference doesn't matter or you know the compiler can figure it out makes sense.

**Comment by chriselrod** [comment]
I added the interpolation support. Will issue a new release soon.
